name: check

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
    types: [synchronize, opened, reopened, edited]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          bazel test --keep_going //...
